apiVersion: v1
kind: Secret
metadata:
  name: docker-registry
data:
  .dockerconfigjson: "WkdWMmIzQnpaV0Z6ZVd4bFlYSnVhVzVuT21SamEzSmZjR0YwWDJWZmJqSXhORjlCTmw5bVdERndPSEU1Yms1R2JYTkpVV3QyUVE9PQ=="
type: kubernetes.io/dockerconfigjson

