version: '2.1'

services:
  ui:
    ports:
      - 8888:8080
    environment:
      - JAVA_OPTS=-XX:MaxRAMPercentage=75.0 -Djava.security.egd=file:/dev/urandom
      - SERVER_TOMCAT_ACCESSLOG_ENABLED=true
      - ENDPOINTS_CATALOG=http://catalog:8080
      - ENDPOINTS_CARTS=http://carts:8080
      - ENDPOINTS_ORDERS=http://orders:8080
      - ENDPOINTS_CHECKOUT=http://checkout:8080
      - ENDPOINTS_ASSETS=http://assets:8080
    hostname: ui
    image: devopseasylearning/a1vincent-ui:v1.0.0
    restart: always
    mem_limit: 256m
    cap_drop:
      - ALL
    networks:
      - revive
    depends_on:
      - catalog
      - carts
      - orders
      - checkout
      - assets

  catalog:
    hostname: catalog
    image: devopseasylearning/a1vincent-catalog:v1.0.0
    restart: always
    environment:
      - GIN_MODE=release
      - DB_PASSWORD=testing
    mem_limit: 128m
    cap_drop:
      - ALL
    networks:
      - revive
    depends_on:
      - catalog-db

  catalog-db:
    image: devopseasylearning/a1vincent-catalog-db:v1.0.0
    hostname: catalog-db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=testing
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=sampledb
      - MYSQL_USER=catalog_user
      - MYSQL_PASSWORD=testing
    mem_limit: 128m
    networks:
      - revive

  carts:
    hostname: carts
    image: devopseasylearning/a1vincent-cart:v1.0.0
    restart: always
    environment:
      - JAVA_OPTS=-XX:MaxRAMPercentage=75.0 -Djava.security.egd=file:/dev/urandom
      - SERVER_TOMCAT_ACCESSLOG_ENABLED=true
      - SPRING_PROFILES_ACTIVE=dynamodb
      - CARTS_DYNAMODB_ENDPOINT=http://carts-db:8000
      - CARTS_DYNAMODB_CREATETABLE=true
      - AWS_ACCESS_KEY_ID=key
      - AWS_SECRET_ACCESS_KEY=dummy
    mem_limit: 256m
    cap_drop:
      - ALL
    networks:
      - revive
    depends_on:
      - carts-db

  carts-db:
    image: devopseasylearning/a1vincent-cart-dynamodb:v1.0.0
    hostname: carts-db
    restart: always
    mem_limit: 256m
    networks:
      - revive

  orders:
    hostname: orders
    image: devopseasylearning/a1vincent-orders:v1.0.0
    restart: always
    environment:
      - JAVA_OPTS=-XX:MaxRAMPercentage=75.0 -Djava.security.egd=file:/dev/urandom
      - SERVER_TOMCAT_ACCESSLOG_ENABLED=true
      - SPRING_PROFILES_ACTIVE=rabbitmq
      - SPRING_DATASOURCE_URL=jdbc:postgresql://orders-db:5432/orders
      - SPRING_DATASOURCE_USERNAME=orders_user
      - SPRING_DATASOURCE_PASSWORD=testing
      - SPRING_RABBITMQ_HOST=rabbitmq
    mem_limit: 256m
    cap_drop:
      - ALL
    networks:
      - revive
    depends_on:
      - rabbitmq
      - orders-db
      - checkout

  orders-db:
    image: devopseasylearning/a1vincent-orders-db:v1.0.0
    hostname: orders-db
    restart: always
    security_opt:
      - no-new-privileges:true
    environment:
      - reschedule=on-node-failure
      - POSTGRES_PASSWORD=testing
      - POSTGRES_DB=orders
      - POSTGRES_USER=orders_user
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d orders -U orders_user"]
      interval: 10s
      timeout: 5s
      retries: 30
    mem_limit: 128m
    networks:
      - revive

  checkout:
    image: devopseasylearning/a1vincent-checkout:v1.0.0
    hostname: checkout
    restart: always
    read_only: true
    tmpfs:
      - /tmp:rw,noexec,nosuid
    environment:
      - REDIS_URL=redis://checkout-redis:6379
      - ENDPOINTS_ORDERS=http://orders:8080
    mem_limit: 256m
    cap_drop:
      - ALL
    networks:
      - revive
    depends_on:
      - checkout-redis

  checkout-redis:
    image: devopseasylearning/a1vincent-checkout-db:v1.0.0
    hostname: checkout-redis
    restart: always
    environment:
      PORT: 8080
    mem_limit: 128m
    networks:
      - revive

  assets:
    hostname: assets
    environment:
      - PORT="8080"
    image: devopseasylearning/a1vincent-assets:v1.0.0
    restart: always
    mem_limit: 64m
    cap_drop:
      - ALL
    networks:
      - revive

  rabbitmq:
    image: devopseasylearning/a1vincent-rabbitmq:v1.0.0
    ports:
      - "5999:5672"
      - "15999:15672"
    networks:
      - revive

networks:
  revive:
    driver: bridge
    ipam:
      config:
        - subnet: 172.0.2.0/24
