---
# Source: a1vincent-espresso-shop-web/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: web-a1vincent-espresso-shop-web
  labels:
    helm.sh/chart: a1vincent-espresso-shop-web-0.1.0
    app.kubernetes.io/name: a1vincent-espresso-shop-web
    app.kubernetes.io/instance: web
    version: v1
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
automountServiceAccountToken: true
---
# Source: a1vincent-espresso-shop-web/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: web-a1vincent-espresso-shop-web
  labels:
    helm.sh/chart: a1vincent-espresso-shop-web-0.1.0
    app.kubernetes.io/name: a1vincent-espresso-shop-web
    app.kubernetes.io/instance: web
    version: v1
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: NodePortP
  ports:
    - port: 8090
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: a1vincent-espresso-shop-web
    app.kubernetes.io/instance: web
    version: v1
---
# Source: a1vincent-espresso-shop-web/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-a1vincent-espresso-shop-web
  labels:
    helm.sh/chart: a1vincent-espresso-shop-web-0.1.0
    app.kubernetes.io/name: a1vincent-espresso-shop-web
    app.kubernetes.io/instance: web
    version: v1
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: a1vincent-espresso-shop-web
      app.kubernetes.io/instance: web
      version: v1
  template:
    metadata:
      labels:
        helm.sh/chart: a1vincent-espresso-shop-web-0.1.0
        app.kubernetes.io/name: a1vincent-espresso-shop-web
        app.kubernetes.io/instance: web
        version: v1
        app.kubernetes.io/version: "1.16.0"
        app.kubernetes.io/managed-by: Helm
    spec:
      serviceAccountName: web-a1vincent-espresso-shop-web
      securityContext:
        {}
      containers:
        - name: a1vincent-espresso-shop-web
          securityContext:
            {}
          image: "devopseasylearning/a1vincent-shop-web:v1.0.0"
          imagePullPolicy: Always
          env:
          - name: ProductCatalogUrl
            value: http://espresso-shop-product-catalog-svc:8091
          - name1: ProductCatalogUrl
            value1: http://espresso-shop-product-catalog-svc:8091
          
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
---
# Source: a1vincent-espresso-shop-web/templates/hpa.yaml
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: web-a1vincent-espresso-shop-web
  labels:
    helm.sh/chart: a1vincent-espresso-shop-web-0.1.0
    app.kubernetes.io/name: a1vincent-espresso-shop-web
    app.kubernetes.io/instance: web
    version: v1
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: web-a1vincent-espresso-shop-web
  minReplicas: 1
  maxReplicas: 100
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
---
# Source: a1vincent-espresso-shop-web/templates/tests/test-connection.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "web-a1vincent-espresso-shop-web-test-connection"
  labels:
    helm.sh/chart: a1vincent-espresso-shop-web-0.1.0
    app.kubernetes.io/name: a1vincent-espresso-shop-web
    app.kubernetes.io/instance: web
    version: v1
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": test
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args: ['web-a1vincent-espresso-shop-web:8090']
  restartPolicy: Never
