apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name }}
data:
   SERVICE_VERSION: v1
   POSTGRES_USER: postgres
   POSTGRES_DB: angel
   POSTGRES_HOST: postgres-postgresql-ha-postgresql